name: athletica
description: Arabic-first SaaS platform for fitness trainers in Egypt
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # Charts and Analytics (used in dashboard)
  fl_chart: ^0.65.0
  
  # Image Handling (used in multiple screens)
  image_picker: ^1.0.4
  
  # Utilities
  shared_preferences: ^2.2.2
  
  # HTTP and API
  dio: ^5.4.0
  
  # Authentication
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Bundle size optimizations
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
