name: athletica
description: Arabic-first SaaS platform for fitness trainers in Egypt
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # Charts and Analytics (used in dashboard)
  fl_chart: ^0.65.0
  
  # Image Handling (used in multiple screens)
  image_picker: ^1.0.4
  
  # Utilities
  shared_preferences: ^2.2.2
  
  # HTTP and API
  dio: ^5.4.0
  
  # Authentication
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^5.0.0
  
  # Deep Linking
  go_router: ^12.1.3
  url_launcher: ^6.2.2
  uni_links: ^0.5.1
  
  # Firebase & Push Notifications
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  firebase_analytics: ^12.0.1
  flutter_local_notifications: ^19.4.1
  permission_handler: ^11.1.0
  timezone: ^0.10.0
  
  # Offline Storage & Sync
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Bundle size optimizations
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
