name: Flutter Web Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - run: flutter pub get

      - run: flutter build web --release --web-renderer html --base-href /athletica/

      - name: Analyze Bundle Size
        run: |
          echo "📊 Bundle Size Analysis:"
          echo "========================"
          find build/web -name "*.js" -exec ls -lh {} \; | head -10
          find build/web -name "*.css" -exec ls -lh {} \;
          du -sh build/web
          echo ""

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
